#!/usr/bin/bash
backlight=/sys/class/backlight/$(ls /sys/class/backlight/ | head -1)
[ -z "$backlight" ] && exit 1
max=$(cat $backlight/max_brightness)
deg=$( bc <<< "scale=2; $max / 100" )
curr=$(cat $backlight/brightness)

if [ -n "$1" ]; then
	case "$1" in
		-*) _new=$( bc <<< "$curr - $deg * ${1/-/}" ) ;;
		+*) _new=$( bc <<< "$curr + $deg * ${1/+/}" ) ;;
		*)  _new=$( bc <<< "$deg * $1" ) ;;
	esac
fi

if [ -n "$_new" ]; then
	new=$( printf "%d\n" $_new 2>/dev/null )
	[ "$new" -gt "$max" ] && new=$max
	[ "$new" -lt "1" ] && new=1
	echo $new | tee $backlight/brightness >/dev/null
fi

curr=$(cat $backlight/brightness)
echo $backlight: $curr
