#!/bin/bash
sudo yaourt -Syu --noconfirm --ignore=squid --ignore=linux --force
yaourt -Su --noconfirm      # linux & squid
# yaourt -S --noconfirm     apps.....
# yaourt -Syu -a --devel --noconfirm
sudo abs -t

vim -c "execute \"PluginInstall!\" | qa"

pacman --root /opt/arch64 -Syu --noconfirm --force
pacman --root /opt/arch32 --config /opt/arch32/etc/pacman.conf --dbpath /opt/arch32/var/lib/pacman/ -Syu --noconfirm --force
yaourt --root /opt/arch64 -Syu --devel -a --noconfirm
pacman --root /opt/arch32 --config /opt/arch32/etc/pacman.conf --dbpath /opt/arch32/var/lib/pacman/ -Syu --devel -a --noconfirm
sudo schroot -c ubuntu -u root -- sh -c "apt-get update; apt-get dist-upgrade -y"

# zeal UPDATE?

mr -d /mnt/Others/git/ update

pip2 list --local --user --outdated | awk '{print $1}' | xargs -n1 pip2 install -U
pip3 list --local --user --outdated | awk '{print $1}' | xargs -n1 pip3 install -U
npm update -g
gem update
#cpan

# kiwix
