#!/bin/bash

function log() {
	echo -e "\e[7;35m${1}\e[;m"
}

log "Updating System PGKs"
sudo yaourt -Syu --noconfirm --force # --ignore=squid --ignore=linux
#yaourt -Su --noconfirm --force      # linux & squid
#yaourt -S  --noconfirm --force    ...

log "Activating InSync"
sudo systemctl start insync@${USER}

log "Download links"
systemctl --user start aria2c.service

log "Download Torrents"
systemctl --user start transmission.service

log "Updating Git/Hg Repos"
mr -d /mnt/Others/git/ update

log "Updating System AURs"
yaourt -Syu -a --devel --noconfirm

log "Updating ABS"
sudo abs 2>/dev/null || sudo abs -t

log "Updating VIM Plugins"
vim -c "execute \"PluginInstall!\" | qa"

log "Updating Arch64 PGKs"
sudo mount LABEL=Arch64 /opt/arch64
sudo pacman --root /opt/arch64 -Syu --noconfirm --force

log "Updating Arch32 PGKs"
sudo mount LABEL=Arch32 /opt/arch32
sudo pacman --root /opt/arch32 --config /opt/arch32/etc/pacman.conf --dbpath /opt/arch32/var/lib/pacman/ -Syu --noconfirm --force

log "Updating Arch64 AURs"
schroot -c Arch64 -- yaourt -Syu --devel -a --noconfirm --force

log "Updating Arch32 AURs"
schroot -c Arch32 -- yaourt -Syu --devel -a --noconfirm --force

# log "Updating Ubuntu PGKs"
# sudo schroot -c ubuntu -u root -- sh -c "apt-get update; apt-get dist-upgrade -y"

# zeal

# kiwix

# ODrive

log "Updating PIP 2"
pip2 list --local --user --outdated | awk 'NR > 2 {print $1}' | xargs -n1 pip2 install -U

log "Updating PIP 3"
pip3 list --local --user --outdated | awk 'NR > 2 {print $1}' | xargs -n1 pip3 install -U

log "Updating NPM"
npm update -g

log "Updating GEM"
gem update

log "Updating CPAN"
cpan -u # -T

log "update pkgfile cache"
sudo pkgfile -u

#log "Updating Docker"
#sudo systemctl start docker.service
#docker images --filter "dangling=false" --format "{{.Repository}}:{{.Tag}}" \
#	| xargs -L1 docker pull
